// Command catalogue — how an analyst, PM or system invokes a skill.
// Surfaces: slash command (in chat), watchlist subscription, scheduled trigger,
// or webhook from another system.

import type { LucideIcon } from "lucide-react";
import { Slash, Bell, Clock, Webhook, Hand } from "lucide-react";

export type CommandSurface = "Slash" | "Watchlist" | "Schedule" | "Webhook" | "Manual";

export const SURFACE_META: Record<CommandSurface, { icon: LucideIcon; tone: string }> = {
  Slash:     { icon: Slash,   tone: "bg-forest/10 text-forest border-forest/30" },
  Watchlist: { icon: Bell,    tone: "bg-enterprise/10 text-enterprise border-enterprise/30" },
  Schedule:  { icon: Clock,   tone: "bg-sand text-taupe border-sand" },
  Webhook:   { icon: Webhook, tone: "bg-destructive/10 text-destructive border-destructive/30" },
  Manual:    { icon: Hand,    tone: "bg-paper text-ink border-sand" },
};

export interface Command {
  id: string;
  trigger: string;
  surface: CommandSurface;
  description: string;
  boundSkillId: string;
  defaultPersona: string;
  scope: string;
  lens: string[];
  owner: string;
  runs7d: number;
  successRate: number;
  lastRun: string;
  installedBy: number;
  tags: string[];
}

export const commands: Command[] = [
  {
    id: "cmd-new-initiative",
    trigger: "/new-initiative {ask}",
    surface: "Slash",
    description: "Spin up a PgMO initiative brief from a free-form ask — auto-fills WIG, scope, dependencies, target state.",
    boundSkillId: "sk-initiative-brief",
    defaultPersona: "PMO Lead",
    scope: "PgMO intake",
    lens: ["MNPI-safe"],
    owner: "PgMO · M. Okafor",
    runs7d: 47, successRate: 99.0, lastRun: "12m ago",
    installedBy: 22, tags: ["intake", "WIG"],
  },
  {
    id: "cmd-status",
    trigger: "/status {initiativeId}",
    surface: "Slash",
    description: "Pull live status for one initiative — lead measures, milestone variance, WIG attainment.",
    boundSkillId: "sk-status-rollup",
    defaultPersona: "PMO Lead",
    scope: "In-flight initiatives",
    lens: ["Information barrier"],
    owner: "PgMO · S. Iyer",
    runs7d: 318, successRate: 99.5, lastRun: "2m ago",
    installedBy: 44, tags: ["status"],
  },
  {
    id: "cmd-weekly",
    trigger: "weekly · Mon 07:00 ET",
    surface: "Schedule",
    description: "Weekly program rollup delivered to sponsors — portfolio health, at-risk flags, whirlwind ratio.",
    boundSkillId: "sk-status-rollup",
    defaultPersona: "PMO Lead",
    scope: "Firm portfolio",
    lens: ["Information barrier"],
    owner: "PgMO · S. Iyer",
    runs7d: 1, successRate: 100, lastRun: "Mon 07:01 ET",
    installedBy: 9, tags: ["weekly", "rollup"],
  },
  {
    id: "cmd-brief",
    trigger: "/brief {ticker}",
    surface: "Slash",
    description: "One-shot morning brief on a name — thesis, catalysts, recent flow, sell-side dispersion.",
    boundSkillId: "sk-thesis-draft",
    defaultPersona: "Equity Analyst",
    scope: "PM coverage · long/short sleeve",
    lens: ["MNPI-safe", "Restricted-list aware"],
    owner: "Research Eng · M. Okafor",
    runs7d: 412, successRate: 98.7, lastRun: "3m ago",
    installedBy: 28, tags: ["morning", "thesis"],
  },
  {
    id: "cmd-thesis",
    trigger: "/thesis {ticker} --side {long|short}",
    surface: "Slash",
    description: "Full thesis drafter with bull/bear/base case. Outputs an IC-ready memo.",
    boundSkillId: "sk-thesis-draft",
    defaultPersona: "Equity Analyst",
    scope: "Active coverage",
    lens: ["MNPI-safe", "Restricted-list aware"],
    owner: "Research Eng · M. Okafor",
    runs7d: 96, successRate: 96.1, lastRun: "47m ago",
    installedBy: 17, tags: ["memo", "IC"],
  },
  {
    id: "cmd-watch",
    trigger: "@catalyst on {watchlist}",
    surface: "Watchlist",
    description: "Subscribes a watchlist to Catalyst Watch — fires when a material event lands.",
    boundSkillId: "sk-catalyst-watch",
    defaultPersona: "Catalyst Monitor",
    scope: "Any PM watchlist",
    lens: ["MNPI-safe"],
    owner: "Research Eng · S. Iyer",
    runs7d: 0, successRate: 100, lastRun: "ambient",
    installedBy: 41, tags: ["alerting"],
  },
  {
    id: "cmd-catalysts",
    trigger: "/catalysts {window}",
    surface: "Slash",
    description: "Forward calendar of catalysts across coverage for a chosen window (7d, 30d, quarter).",
    boundSkillId: "sk-catalyst-watch",
    defaultPersona: "Catalyst Monitor",
    scope: "Firm coverage",
    lens: ["MNPI-safe"],
    owner: "Research Eng · S. Iyer",
    runs7d: 188, successRate: 99.2, lastRun: "11m ago",
    installedBy: 23, tags: ["calendar"],
  },
  {
    id: "cmd-call",
    trigger: "earnings-call → delta",
    surface: "Webhook",
    description: "On any new earnings call transcript, score tone & guidance delta vs. prior 4 quarters.",
    boundSkillId: "sk-earnings-delta",
    defaultPersona: "Earnings Reader",
    scope: "All names in firm coverage",
    lens: ["MNPI-safe", "Public-only sources"],
    owner: "Quant · D. Hwang",
    runs7d: 312, successRate: 99.7, lastRun: "2h ago",
    installedBy: 12, tags: ["earnings", "automation"],
  },
  {
    id: "cmd-sheet",
    trigger: "/sheet {ticker}",
    surface: "Slash",
    description: "Generate a one-page tear sheet for any name in coverage.",
    boundSkillId: "sk-tear-sheet",
    defaultPersona: "Equity Analyst",
    scope: "Firm universe",
    lens: ["Public-only sources"],
    owner: "Data Eng · J. Lin",
    runs7d: 1102, successRate: 99.9, lastRun: "1m ago",
    installedBy: 56, tags: ["snapshot"],
  },
  {
    id: "cmd-redteam",
    trigger: "/redteam {id}",
    surface: "Slash",
    description: "Spin up a red-team pre-mortem against an open thesis or initiative before steerco/IC.",
    boundSkillId: "sk-premortem",
    defaultPersona: "Devil's Advocate",
    scope: "Any open thesis or initiative",
    lens: ["MNPI-safe"],
    owner: "Research · R. Klein",
    runs7d: 38, successRate: 92.1, lastRun: "5h ago",
    installedBy: 9, tags: ["risk", "IC prep"],
  },
  {
    id: "cmd-attrib",
    trigger: "weekly · Mon 06:30 ET",
    surface: "Schedule",
    description: "Weekly post-trade attribution across closed positions, mailed to each originating analyst.",
    boundSkillId: "sk-attribution",
    defaultPersona: "Attribution Bot",
    scope: "All firm sleeves",
    lens: ["Information barrier"],
    owner: "Quant · D. Hwang",
    runs7d: 1, successRate: 100, lastRun: "Mon 06:31 ET",
    installedBy: 4, tags: ["P&L", "weekly"],
  },
  {
    id: "cmd-houseview",
    trigger: "/houseview {noteId}",
    surface: "Slash",
    description: "Reconcile a draft note against the firm's house view; surface divergence.",
    boundSkillId: "sk-house-view",
    defaultPersona: "House View Steward",
    scope: "Macro & cross-asset notes",
    lens: ["Information barrier"],
    owner: "CIO Office",
    runs7d: 21, successRate: 100, lastRun: "Yesterday",
    installedBy: 6, tags: ["governance"],
  },
  {
    id: "cmd-backtest",
    trigger: "/backtest {signalId}",
    surface: "Slash",
    description: "Walk-forward backtest against the paper sleeve with realistic frictions.",
    boundSkillId: "sk-signal-backtest",
    defaultPersona: "Quant Researcher",
    scope: "Quant sandbox",
    lens: ["Public-only sources"],
    owner: "Quant · D. Hwang",
    runs7d: 64, successRate: 97.0, lastRun: "26m ago",
    installedBy: 8, tags: ["backtest"],
  },
  {
    id: "cmd-flex",
    trigger: "/flex {modelId}",
    surface: "Slash",
    description: "Stress an analyst's working model across rev/margin/multiple scenarios.",
    boundSkillId: "sk-model-flex",
    defaultPersona: "Quant Researcher",
    scope: "Model library",
    lens: ["Information barrier"],
    owner: "Quant · L. Vance",
    runs7d: 73, successRate: 99.0, lastRun: "1h ago",
    installedBy: 11, tags: ["model"],
  },
  {
    id: "cmd-screen",
    trigger: "publish → MNPI lens",
    surface: "Webhook",
    description: "Required pre-flight on every outbound artifact. Approve / hold / escalate.",
    boundSkillId: "sk-mnpi-screen",
    defaultPersona: "Compliance Gate",
    scope: "Firm-wide",
    lens: ["MNPI-safe", "Restricted-list aware", "Information barrier"],
    owner: "Compliance · J. Park",
    runs7d: 3091, successRate: 99.95, lastRun: "12s ago",
    installedBy: 0, tags: ["compliance", "required"],
  },
  {
    id: "cmd-initiate",
    trigger: "/initiate {ticker}",
    surface: "Slash",
    description: "Bootstrap full coverage of a new name — peer set, KPI tree, draft thesis.",
    boundSkillId: "sk-coverage-initiate",
    defaultPersona: "Equity Analyst",
    scope: "New-name pipeline",
    lens: ["MNPI-safe"],
    owner: "Research · R. Klein",
    runs7d: 9, successRate: 100, lastRun: "Yesterday",
    installedBy: 5, tags: ["coverage"],
  },
];