/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as InitiativesRouteImport } from './routes/initiatives'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchThreadIdRouteImport } from './routes/research.$threadId'
import { Route as InitiativesIdRouteImport } from './routes/initiatives.$id'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesRoute = InitiativesRouteImport.update({
  id: '/initiatives',
  path: '/initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchRoute,
} as any)
const ResearchThreadIdRoute = ResearchThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ResearchRoute,
} as any)
const InitiativesIdRoute = InitiativesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InitiativesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/commands': typeof CommandsRoute
  '/glossary': typeof GlossaryRoute
  '/initiatives': typeof InitiativesRouteWithChildren
  '/research': typeof ResearchRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/initiatives/$id': typeof InitiativesIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/commands': typeof CommandsRoute
  '/glossary': typeof GlossaryRoute
  '/initiatives': typeof InitiativesRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/initiatives/$id': typeof InitiativesIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/commands': typeof CommandsRoute
  '/glossary': typeof GlossaryRoute
  '/initiatives': typeof InitiativesRouteWithChildren
  '/research': typeof ResearchRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/workflows': typeof WorkflowsRoute
  '/initiatives/$id': typeof InitiativesIdRoute
  '/research/$threadId': typeof ResearchThreadIdRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/commands'
    | '/glossary'
    | '/initiatives'
    | '/research'
    | '/roadmap'
    | '/sitemap.xml'
    | '/skills'
    | '/workflows'
    | '/initiatives/$id'
    | '/research/$threadId'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/commands'
    | '/glossary'
    | '/initiatives'
    | '/roadmap'
    | '/sitemap.xml'
    | '/skills'
    | '/workflows'
    | '/initiatives/$id'
    | '/research/$threadId'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/commands'
    | '/glossary'
    | '/initiatives'
    | '/research'
    | '/roadmap'
    | '/sitemap.xml'
    | '/skills'
    | '/workflows'
    | '/initiatives/$id'
    | '/research/$threadId'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CommandsRoute: typeof CommandsRoute
  GlossaryRoute: typeof GlossaryRoute
  InitiativesRoute: typeof InitiativesRouteWithChildren
  ResearchRoute: typeof ResearchRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives': {
      id: '/initiatives'
      path: '/initiatives'
      fullPath: '/initiatives'
      preLoaderRoute: typeof InitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/research/$threadId': {
      id: '/research/$threadId'
      path: '/$threadId'
      fullPath: '/research/$threadId'
      preLoaderRoute: typeof ResearchThreadIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/initiatives/$id': {
      id: '/initiatives/$id'
      path: '/$id'
      fullPath: '/initiatives/$id'
      preLoaderRoute: typeof InitiativesIdRouteImport
      parentRoute: typeof InitiativesRoute
    }
  }
}

interface InitiativesRouteChildren {
  InitiativesIdRoute: typeof InitiativesIdRoute
}

const InitiativesRouteChildren: InitiativesRouteChildren = {
  InitiativesIdRoute: InitiativesIdRoute,
}

const InitiativesRouteWithChildren = InitiativesRoute._addFileChildren(
  InitiativesRouteChildren,
)

interface ResearchRouteChildren {
  ResearchThreadIdRoute: typeof ResearchThreadIdRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchThreadIdRoute: ResearchThreadIdRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CommandsRoute: CommandsRoute,
  GlossaryRoute: GlossaryRoute,
  InitiativesRoute: InitiativesRouteWithChildren,
  ResearchRoute: ResearchRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
